name: Test

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GO_VERSION: "1.22.x"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
          - macos-12
          - macos-13
          - macos-14

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Run test
        run: go test -v ./test/...
